### ISSUE TITLE
Docker Hub verions

### ISSUE THREAD

**Issue by lonnieOST** [pschiffe/docker-pdns#1]
Hello,

I tried to run your ansible-playbook.yml to create a docker container, but it failed with an error about unknown c_state (16)

I have a MySQL cluster setup and would like to run your docker-pdns to connect to it as well.

Is there a docker image available on Docker Hub (https://hub.docker.com/)

Maybe I can pull it from there?

Thanks,
Lonnie

**Comment by almereyda** [comment]
In the README you will find mentionned the two images of desire for you:

* `pschiffe/pdns-mysql`
* `pschiffe/pdns-admin`

I am considering a pull request which includes a `docker-compose.yml` file, to specify this a little further.

**Comment by lonnieOST** [comment]
Yes, thanks for this as I did see it in the README, but I did not completely understand how to do a simple invocation of each one as the examples shown seem to be too complex for any simple usage.

I just need to run the "pschiffe/pdns-mysql" and have it connect to an external mysql database cluster that I will be bringing up as well and then use the second container "pschiffe/pdns-admin" to access the first one.

In the README, you do not explicitly show a command to start up a simple call for the pdns-mysql and then show some environmental variables:

(name=default value)

PDNS_gmysql_host=mysql
PDNS_gmysql_port=3306
PDNS_gmysql_user=root
PDNS_gmysql_password=powerdns
PDNS_gmysql_dbname=powerdns

But, am still new to trying to use these containers in docker.

You do show a complex example of running a MASTER/SLAVE PowerDNS example for which I may need to figure out how to start up in a simple way as well, but my first objective is to just start a single instance of pdns-mysql and connect to my external mysql database and then start up the pdns-admin to administrate the pdns-mysql.

Thanks again,

**Comment by pschiffe** [comment]
Hi @lonnieOST , I'm really sorry it took me so long to write a reply, but here it is. Ansible playbook should be fixed by now. The readme contains all the examples. For example, to specify env var for a container, you need to use the `-e` option. So in your case, if you want to create one single container with powerdns connected to your external mysql, the command may look like this:
```
docker run -d -p 53:53 -p 53:53/udp --name pdns-master \
  --hostname ns1.example.com \
  -e PDNS_gmysql_host=mysql \
  -e PDNS_gmysql_port=3306 \
  -e PDNS_gmysql_user=root \
  -e PDNS_gmysql_password=powerdns \
  -e PDNS_gmysql_dbname=powerdns \
  pschiffe/pdns-mysql
```

The rest is basically optional, and can be tweaked to your needs.

@almereyda if you have docker-compose file available, please do a PR! It would be appreciated.
