### ISSUE TITLE
Outdated containers on hub.docker.com

### ISSUE THREAD

**Issue by aneagoe** [pschiffe/docker-pdns#13]
Would be great to have new builds pushed to docker hub. Even better, it would be nice to have a pipeline or an automated build process that can push to docker hub whenever a new PowerDNS version is released.

**Comment by xyzxyz442** [comment]
You can use from this [image](https://hub.docker.com/r/xyzxyz442/pdns-recursor/) that I forked from this repo and update the alpine version to latest which will change recursor from 4.0.7 to 4.1.x.

**Comment by aneagoe** [comment]
@xyzxyz442 thanks for the link. Of course I can also just build it from the Dockerfile or fork it, it's not a big inconvenience but having a proper pipeline to build and deliver to dockerhub would be great for this project. It would also enable people to contribute more instead of forking just to get newer versions.

**Comment by aneagoe** [comment]
Found this really simple [guide](https://cinhtau.net/2016/09/01/use-travis-ci-in-github-to-build-and-deploy-to-dockerhub/) to setup travis ci for building and pushing to dockerhub. It most likely makes sense that the github repo owner sets up the travis ci account but afterward anyone can contribute.

**Comment by xyzxyz442** [comment]
@aneagoe I see you point. For now, I linked alpine repo to the image for hub.docker to trigger automated build if base image is updated.

**Comment by pschiffe** [comment]
Hey guys, I've just triggered build for all images in this repo. You don't need travis to connect github and docker hub for ci - docker hub can build images automatically on `git push` to github, or when a new base image for your image is published.. I have this configured since beginning, but docker hub just ignored it for a while -_-

That being said, I'm using pdns packages from either Fedora or Alpine, so I don't think that there will be new versions available unless the base images are updated. I do have some tasks for this repo in my todo, but because of lack of time.. you know it. I will happily accept PRs which updates base images, or other improvements..

Next week there is a new Fedora 29 release, maybe that would be a good reason for me to update these images. I'll see how I'll manage.

**Comment by aneagoe** [comment]
Thanks a lot @pschiffe. I will look at updating the alpine image and send a PR for that. By the looks of it it builds just fine, so bumping from 3.7 to 3.8 would get us a PDNS version of 4.1.3.

**Comment by aneagoe** [comment]
Since builds have resumed again, this can be closed.
