### ISSUE TITLE
powerdns-admin 0.4.2

### ISSUE THREAD

**Issue by patobest** [pschiffe/docker-pdns#141]
Hi Peter, 

Are you planning to move to latest pdns-admin version?, I see Dockerfile points to 0.4.1 version , Did you find any issue with newer version 0.4.2?

Thanks for all your hard work on this proyect! 
Patricio.

**Comment by pschiffe** [comment]
Hi Patricio,

yeah, I've tried to move to the pdns-admin version 0.4.2, but it didn't really work for me, there were session issues, which should be fixed in the next version. Now I'm just waiting for the next release and I'll try again.

https://github.com/PowerDNS-Admin/PowerDNS-Admin/milestone/7

peter

**Comment by patobest** [comment]
thank you Peter!
