### ISSUE TITLE
Versioning of Releases

### ISSUE THREAD

**Issue by gruppferi** [pschiffe/docker-pdns#42]
Hi,
In dockerfile it do curl ([this line](https://github.com/pschiffe/docker-pdns/blob/master/pdns-admin-static/Dockerfile#L6)) and get the latest from pdns master branch, as user you may want to install specific branch, or better to say you already installed with current format, your pdns version maybe 4.3.x and due to some issues after a while you try to redeploy the docker file or ansible playbook, you will land to new pdns version something like 4.5.0.
The only thing currently is versioned is phpmyadmin and MariaDB
### Suggestion:
1. either curl command in dockerfile done from specific tags from pdns which corresponds to a release/version 
2. dockers in docker hub be taged for each pdns version
### Problem with Current situation:
1. unwanted update/upgrade
2. No control for users to stay with specific version
3. Danger that sometimes in master wouldn't be stable version/release
 
I would be happy to elaborate and kinda help to make it possible.

**Comment by pschiffe** [comment]
Hey @gruppferi ,

thanks for your feedback. The linked Dockerfile is deprecated, I'm keeping it here for historic reasons, but I should remove it by now.

Anyway, the current version is similar in that, [see here](https://github.com/pschiffe/docker-pdns/blob/master/pdns-admin-base-ngoduykhanh/Dockerfile#L14). The reason is that there is very little activity and only a handful of [releases](https://github.com/ngoduykhanh/PowerDNS-Admin/tags) and [changes](https://github.com/ngoduykhanh/PowerDNS-Admin/commits/master), so for the current situation this approach looks better to me. If the situation change and activity increases, than I totally agree I would need to use versions/tags.

peter

**Comment by gruppferi** [comment]
@pschiffe  thanks for info, actually my big concern is with PDNS container itself, I have issue now with PTR as I use restAPI to create zone and records through another application automatically. in new version of PDNS PTR is deprecated.
I need to redeploy my ansible stack and by this the version was also updated and caused PTR deprecation ERROR.

**Comment by pschiffe** [comment]
Ah I see. I may introduce the tags for pdns and pdns resolver, that shouldn't be too much hassle.

**Comment by gruppferi** [comment]
@pschiffe that would be a big help, thanks in advance for it

**Comment by pschiffe** [comment]
Hello, `pschiffe/pdns-recursor` and `pschiffe/pdns-mysql` images are from now on versioned on docker hub :-)
