### ISSUE TITLE
Forward zones from recursor doesnt work 

### ISSUE THREAD

**Issue by UrosCvijanovic** [pschiffe/docker-pdns#98]
I have a docker-compose file to run the authoritative dns server together with recursor configured like this: 

version: '3'

services:
  db:
    image: mariadb:10-jessie
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=powerdnsadmin
      - MYSQL_USER=lradmin
      - MYSQL_PASSWORD=lrpdns
    ports:
      - 3306:3306
    restart: always
    volumes:
      - /pdns-mysql:/var/lib/mysql
  pdns-recursor:
    image: pschiffe/pdns-recursor:alpine
    ports:
      - '53:53'
      - '53:53/udp'
    environment:
      - PDNS_api_key=secret
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=secret2
      - PDNS_forward-zones=lrdevelop.com.=192.168.1.37:54
  pdns:
    image: pschiffe/pdns-mysql:alpine
    hostname: pdns
    domainname: lrdevelop.com
    restart: always
    depends_on:
      - db
    ports:
      - "54:53"
      - "54:53/udp"
      - "8081:8081"
    environment:
      - PDNS_gmysql_host=db
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=lradmin
      - PDNS_gmysql_dbname=powerdnsadmin
      - PDNS_gmysql_password=lrpdns
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=secret
      - PDNSCONF_API_KEY=secret
      - PDNS_webserver=yes
      - PDNS_webserver-allow-from=127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.0.0.0/24,192.168.1.0/24
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=secret2
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_allow_notify_from=0.0.0.0
      - PDNS_allow_axfr_ips=127.0.0.1

  web_app:
    image: powerdnsadmin/pda-legacy:latest
    container_name: powerdns_admin
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://lradmin:lrpdns@db/powerdnsadmin
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
      - OFFLINE_MODE=False

For some reason the recursor is not forwarding request to the authoritative dns server to resolve the custom domains. Can someone help?

**Comment by pschiffe** [comment]
Hi @UrosCvijanovic , do you have some logs from the recursor when you try to query the domain? What are IPs of the containers?

**Comment by UrosCvijanovic** [comment]
Hi @pschiffe. No there are no logs for the recursor. The IP should be the same, its the ip of the VM i am running container on. I forwarding DNS requests from recursor to auth dns via port 54 (- PDNS_forward-zones=lrdevelop.com.=192.168.1.37:54). The performance is quite strange as auth dns server works by itself (without recursor service) - it resolves the custom domains I register in the database , but once I include recursor the global domains (eg. google.com) are resolved, while custom ones that should be forwarded to auth are not resolved.

**Comment by pschiffe** [comment]
Could you print here the `/etc/pdns/recursor.conf` file from the recursor? Whether the config `PDNS_forward-zones=lrdevelop.com.=192.168.1.37:54` is properly propagated, maybe quotes will be needed there.

**Comment by pschiffe** [comment]
Also provide `docker inspect pdns-recursor` pls.

**Comment by pschiffe** [comment]
Feel free to reopen if needed.

**Comment by Isnubi** [comment]
Hello, I reopen this issue because I'm facing it actually.
I'm trying to configure a pdns authoritative server and a pdns-recursor along, like that:
![image](https://github.com/pschiffe/docker-pdns/assets/40593456/4a886419-530e-440e-892d-3e4f15a60a1b)

I'm facing the same issue, that is the recursor don't forward the zone that I give to it.
The configuration line in the docker compose is well given to the container, here the recursor.conf file:
`
[root@1b26e68a614e /]# cat /etc/pdns-recursor/recursor.conf
aggressive-nsec-cache-size=0
allow-from=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
daemon=no
dnssec=off
forward-zones=test.local10.0.3.251:5300
local-address=0.0.0.0
local-port=53
log-common-errors=yes
logging-facility=0
loglevel=6
quiet=no
setgid=pdns-recursor
setuid=pdns-recursor
`

For more context, when I try to dig a DNS entry on port 53, i got a SERVFAIL return. If I try to dig a external DNS (like google.com), it returns me the IP, via the external DNS i give to the host (here, 1.1.1.1).
But, when I do a dig, on the port of the pdns authoritative server (5300 here), it returns me the IP of my DNS entry.

I give you the three dig requests I do:
`
dig docker.test.local @10.0.3.251

; <<>> DiG 9.18.19-1~deb12u1-Debian <<>> docker.test.local@10.0.3.251
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 57434
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;docker.test.local. IN      A

;; Query time: 1508 msec
;; SERVER: 10.0.3.251#53(10.0.3.251) (UDP)
;; WHEN: Sat Oct 21 09:02:06 EDT 2023
;; MSG SIZE  rcvd: 46
`
`
dig google.com @10.0.3.251

; <<>> DiG 9.18.19-1~deb12u1-Debian <<>> google.com @10.0.3.251
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64545
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             300     IN      A       142.250.179.78

;; Query time: 64 msec
;; SERVER: 10.0.3.251#53(10.0.3.251) (UDP)
;; WHEN: Sat Oct 21 09:02:22 EDT 2023
;; MSG SIZE  rcvd: 55
`
`
dig docker.test.local @10.0.3.251 -p 5300

; <<>> DiG 9.18.19-1~deb12u1-Debian <<>> docker.test.local@10.0.3.251 -p 5300
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53457
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;docker.test.local. IN      A

;; ANSWER SECTION:
docker.test.local.      60      IN      A       10.0.3.1

;; Query time: 20 msec
;; SERVER: 10.0.3.251#5300(10.0.3.251) (UDP)
;; WHEN: Sat Oct 21 09:06:00 EDT 2023
;; MSG SIZE  rcvd: 62
```
